version: "3"

services:
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-fluentd:2.1
    user: root
    tty: true
    volumes:
      - ./fluent.conf:/etc/fluentd/fluent.conf
      - ./apache_logs:/home/root/apache_logs
      - ./flush_logs.py:/home/root/flush_logs.py
      - ./source:/fluentd/source
      - ./target:/fluentd/target
    working_dir: /home/root

networks:
  default:
    name: default_network
