version: "3"

services:
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-fluentd:2.1
    user: root
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./fluent.conf:/etc/fluentd/fluent.conf
    working_dir: /home/root

networks:
  default:
    name: default_network
