version: '3'

services:
  ubuntu:
    container_name: ubuntu
    image: psyoblade/data-engineer-ubuntu:20.04
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./fortune_teller.sh:/fortune_teller.sh
    entrypoint: [ "/fortune_teller.sh", "1000" ]
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-async: "true"
        fluentd-address: localhost:24224
        tag: docker.fortune
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-fluentd:2.2
    user: root
    stdin_open: true
    tty: true
    ports:
      - 24224:24224
    volumes:
      - ./fluent.conf:/etc/fluentd/fluent.conf
    entrypoint: [ "/home/root/fluentd" ]
    working_dir: /home/root

networks:
  default:
    name: day2_ex5_network
